### ISSUE TITLE
Unable to compile without g++

### ISSUE THREAD

**Issue by inuum** [gwstaten/wordl#3]
process_begin: CreateProcess(NULL, g++ -Wall -Iinclude -MMD -MP -static -std=c++17 -c src/main.cpp -o bin/main.o, ...) failed.
make (e=2): The system cannot find the file specified.
makefile:22: recipe for target 'bin/main.o' failed
make: *** [bin/main.o] Error 2

**Comment by RangerEmerald** [comment]
What operating system are you using?

**Comment by inuum** [comment]
Windows 11 Home 10.0.22000 Build 22000

**Comment by RangerEmerald** [comment]
Can you type `gcc -v` in the command prompt and show what it outputs?

**Comment by inuum** [comment]
'g++' is not recognized as an internal or external command,
operable program or batch file.

**Comment by inuum** [comment]
also btw can you just provide like a prebuilt exe in releases or something?

**Comment by RangerEmerald** [comment]
Can you try compiling it again with the new makefile?

**Comment by RangerEmerald** [comment]
I'll see about prebuilt executables

**Comment by inuum** [comment]
hmm. now it gives this error

process_begin: CreateProcess(NULL, c++ -g -Wall -Iinclude -MMD -MP -static -std=c++17 -c src/main.cpp -o bin/main.o, ...) failed.
make (e=2): The system cannot find the file specified.
makefile:22: recipe for target 'bin/main.o' failed
make: *** [bin/main.o] Error 2

**Comment by RangerEmerald** [comment]
Do you have c++ installed? What does `c++ -v` output? The code requires c++17

**Comment by inuum** [comment]
'c++' is not recognized as an internal or external command,
operable program or batch file.. i have c++ build tools tho so its weird.

**Comment by inuum** [comment]
i'm downloading c++ right now, but you should probably add c++ as a prerequisite to the readme
